pipeline:
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gowtham_nanda
        repoName: spring-petclinic-demo
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhub_connecter
                    image: maven:3.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean package -DskipTests -Dcheckstyle.skip=true
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkalipalliGCPConnector
                    host: us.gcr.io
                    projectID: bustling-tuner-482104-a0
                    imageName: harness-demo
                    tags:
                      - v1
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: v1
                      name: us.gcr.io/harness-demo
                      domain: us-central1-docker.pkg.dev
                    sbom:
                      format: spdx-json
          buildIntelligence:
            enabled: false
  identifier: gkalipallidemocicdlatest_Clone
  name: gkalipalli-demo-cicd-latest - Clone
