pipeline:
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gowtham_nanda
        repoName: spring-petclinic-demo
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhub_connecter
                    image: maven:3.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean package -DskipTests -Dcheckstyle.skip=true
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkalipalliGCPConnector
                    host: us.gcr.io
                    projectID: bustling-tuner-482104-a0
                    imageName: harness-demo
                    tags:
                      - v1
          buildIntelligence:
            enabled: false
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gkalipalliservice
          environment:
            environmentRef: gkalipallidev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gkalipalliinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: gkalipallidemocicdlatest_Clone
  name: gkalipalli-demo-cicd-latest - Clone
